services:
  db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
  